image: openbsd/7.0
sources:
  - https://git.sr.ht/~josegpt/dotfiles
secrets:
  - 81224313-da56-4122-b953-6e49852e5cd7
tasks:
  - setup: |
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
  - mirror: |
      cd dotfiles
      git remote add mirror git@github.com:josegpt/dotfiles.git
      git push mirror main
