#!/bin/sh

_die() {
    echo "${1:-usage: ${0##*/}} <desktop|laptop|packages>" >&2
    exit 1
}

type stow > /dev/null 2>&1 || _die "error: install stow before deploying"

_() {
    stow -t $HOME "$@"
}

case $1 in
    desktop|laptop) _ emacs git bin gnupg isync mpv x ;;
    packages) doas pkg_add -l ./packages ;;
    *) echo "error: unknown computer \`$1'"; _die
esac
