#!/bin/sh

_die() {
    echo "${1:-usage: ${0##*/}} <desktop|laptop>" >&2
    exit 1
}

type stow > /dev/null 2>&1 || _die "error: install stow before deploying"

_() {
    stow -t $HOME "$@"
}

_handler() {
    case $1 in
        desktop|laptop) _ emacs git alsa service shell w ;;
        *) echo "error: unknown computer \`$1'"; _die
    esac
}

for a in $@; do
    _handler $a
done
