#!/bin/sh

_die() {
    echo "${1:-usage: ${0##*/}} <desktop|laptop>" >&2
    exit 1
}

type stow > /dev/null 2>&1 || _die "error: install stow before deploying"

_() {
    stow -t $HOME "$@"
}

_handler() {
    echo "deploying $1"
    case $1 in
        desktop|laptop) _ emacs git gnupg alsa shell x ;;
        *) echo "error: unknown computer \`$1'"; _die
    esac
    echo "deploying $1 done"
}

for a in $@; do
    _handler $a
done
