#!/bin/sh

_die() {
    echo "${1:-usage: ${0##*/}} <desktop|laptop|packages>..." >&2
    exit 1
}

type stow > /dev/null 2>&1 || _die "error: stow must be installed"

_() {
    stow -t $HOME "$@"
}

_handler() {
    case $1 in
        desktop|laptop) _ emacs git shell gtk x ;;
        packages) doas pkg_add -l ./packages ;;
        *) echo "error: unknown option \`$1'"; _die
    esac
}

for a in $@; do
    _handler $a
done
