#!/usr/bin/env bash

Date() {
    DATE=$(date "+%a %B %d, %Y")
    echo "$DATE"
}

Clock() {
    CLOCK=$(date "+%I:%M%P")
    echo "$CLOCK"
}

while true; do
    echo "%{c} $(Clock) %{r} $(Date)"
    sleep .1s
done
