#!/bin/sh

Clock() {
  TIME=$(date "+%H:%M:%S")
  echo "$TIME"
}

Date() {
  DATE=$(date "+%a, %m %B %Y")
  echo "$DATE"
}

Battery() {
  BATTPRCT=$(acpiconf -i 1 | grep -i 'Remaining c')
  BATTTIME=$(acpiconf -i 1 | grep -i 'Remaining t')
  echo "$BATTPRCT | $BATTTIME"
}

# kill all process
#killall -9 lemonbar xtitle xdo clock

while true; do
  echo -e "%{c}$(Clock) - $(Date)" "%{r}$(Battery)"
  sleep 1
done

