#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

# constants
MOD=Mod4
RESIZESTEP=0.05
TAG_NAMES=({1..5})
TAG_KEYS=({1..5})
BG='#ffffff'
FG='#000000'
WEAK='#888888'
WEAKER='#dddddd'
WEAKEST='#efefef'
HL='#fda50f'
WG='#ff0000'
SCS='#00ff00'
S='#3c5e2b'
# gentoo uses the old path for emacs server
USERID=$(id -u)
EMACSCLIENT="/tmp/emacs${USERID}/server"

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# tags
hc rename default "${TAG_NAMES[0]}" || true
for i in "${!TAG_NAMES[@]}" ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$MOD-Shift-$key" use_index "$i"
        hc keybind "$MOD-Control-$key" move_index "$i"
    fi
done

# spawns
hc keybind $MOD-e spawn emacsclient -s $EMACSCLIENT -c
hc keybind $MOD-Return spawn emacsclient -s $EMACSCLIENT -c -e "(term \"/bin/bash\")"
hc keybind $MOD-i spawn dmenu_run -nb $BG -nf $FG -sb $HL -sf $FG -b
hc keybind $MOD-r spawn emacsclient -s $EMACSCLIENT -c -e "(elfeed)"
hc keybind XF86MonBrightnessUp spawn xbacklight -inc 10%
hc keybind XF86MonBrightnessDown spawn xbacklight -dec 10%
hc keybind XF86AudioRaiseVolume spawn amixer set Master 10%+
hc keybind XF86AudioLowerVolume spawn amixer set Master 10%-
hc keybind XF86AudioMute spawn amixer set Master toggle
hc keybind XF86AudioMicMute spawn amixer set Capture toggle

# wm
hc keybind $MOD-q           reload
hc keybind $MOD-Shift-q     quit

# focus
hc keybind $MOD-o           cycle_all
hc keybind $MOD-Shift-o     cycle_monitor
hc keybind $MOD-u jumpto    urgent
hc keybind $MOD-period      use_index +1 --skip-visible
hc keybind $MOD-comma       use_index -1 --skip-visible
hc keybind $MOD-b           focus left
hc keybind $MOD-n           focus down
hc keybind $MOD-p           focus up
hc keybind $MOD-f           focus right

# layout
hc keybind $MOD-0           close_and_remove
hc keybind $MOD-1           fullscreen toggle
hc keybind $MOD-space       floating toggle
hc keybind $MOD-2           split bottom 0.5
hc keybind $MOD-3           split right 0.5
hc keybind $MOD-k           close
hc keybind $MOD-Shift-b     shift left
hc keybind $MOD-Shift-n     shift down
hc keybind $MOD-Shift-p     shift up
hc keybind $MOD-Shift-f     shift right
hc keybind $MOD-Control-b   resize left +$RESIZESTEP
hc keybind $MOD-Control-n   resize down +$RESIZESTEP
hc keybind $MOD-Control-p   resize up +$RESIZESTEP
hc keybind $MOD-Control-f   resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $MOD-Button1   move
hc mousebind $MOD-Button2   zoom
hc mousebind $MOD-Button3   resize

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color $HL
hc set frame_border_normal_color $WEAK
hc set frame_bg_normal_color $WEAK
hc set frame_bg_active_color $BG
hc set frame_border_width 0
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 4
hc set frame_gap 4

hc attr theme.active.color $HL
hc attr theme.normal.color $WEAKER
hc attr theme.urgent.color $WG
hc attr theme.inner_width 0
hc attr theme.inner_color $BG
hc attr theme.border_width 4
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color $BG
hc attr theme.active.inner_color $HL
hc attr theme.urgent.inner_color $WG
hc attr theme.normal.inner_color $BG
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.active.outer_width 0
hc attr theme.background_color $COLOR_NB

hc set window_gap 4
hc set frame_padding 4
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

# rules
hc unrule -F
hc rule class=Firefox tag=5
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors
