#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

# Gentoo uses the old path for emacs server
USERID=$(id -u)
EMACSCLIENT="/tmp/emacs${USERID}/server"

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4

# tags
tag_names=({1..5})
tag_keys=({1..5})

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
done

hc keybind $Mod-Shift-q quit
hc keybind $Mod-q reload
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-k close 
hc keybind $Mod-o cycle_all
hc keybind $Mod-Shift-o cycle_monitor
hc keybind $Mod-n use_index +1 --skip-visible
hc keybind $Mod-p use_index -1 --skip-visible
hc keybind $Mod-1 fullscreen toggle
hc keybind $Mod-0 close_and_remove
hc keybind $Mod-2 split bottom 0.5
hc keybind $Mod-3 split right 0.5
hc keybind $Mod-e spawn emacsclient -s $EMACSCLIENT -c
hc keybind $Mod-f spawn emacsclient -s $EMACSCLIENT -c -e "(elfeed)"
hc keybind $Mod-m spawn emacsclient -s $EMACSCLIENT -c -e "(mu4e)"
hc keybind $Mod-Return spawn emacsclient -s $EMACSCLIENT -c -e "(term \"/bin/bash\")"
hc keybind $Mod-r spawn dmenu_run -nb '#282828' -nf '#d5c4a1' -sb '#d65d0e' -sf '#ebdbb2'
hc keybind $Mod-t pseudotile toggle
hc keybind XF86MonBrightnessUp spawn xbacklight -inc 10%
hc keybind XF86MonBrightnessDown spawn xbacklight -dec 10%
hc keybind XF86AudioRaiseVolume spawn amixer set Master 10%+
hc keybind XF86AudioLowerVolume spawn amixer set Master 10%-
hc keybind XF86AudioMute spawn amixer set Master toggle
hc keybind XF86AudioMicMute spawn amixer set Capture toggle

# moving clients in tiling and floating mode
# hc keybind $Mod-Shift-Left  shift left
# hc keybind $Mod-Shift-Down  shift down
# hc keybind $Mod-Shift-Up    shift up
# hc keybind $Mod-Shift-Right shift right

# resizing frames and floating clients
# resizestep=0.05
# hc keybind $Mod-Control-Left       resize left +$resizestep
# hc keybind $Mod-Control-Down       resize down +$resizestep
# hc keybind $Mod-Control-Up         resize up +$resizestep
# hc keybind $Mod-Control-Right      resize right +$resizestep

# mouse
hc mouseunbind --all
# hc mousebind $Mod-Button1 move
# hc mousebind $Mod-Button2 zoom
# hc mousebind $Mod-Button3 resize

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#3c3836'
hc set frame_border_normal_color '#282828'
hc set frame_bg_normal_color '#1d2021'
hc set frame_bg_active_color '#d65d0e'
hc set frame_border_width 4
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 4
hc set frame_gap 4

hc attr theme.title_height 0
hc attr theme.padding_top 0
hc attr theme.active.color '#d65d0e'
hc attr theme.normal.color '#1d2021'
hc attr theme.urgent.color '#b8bb26'
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#d65d0e'
hc attr theme.urgent.inner_color '#cc241d'
hc attr theme.normal.inner_color '#282828'
hc attr theme.active.outer_width 1
hc attr theme.background_color '#282828'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

# rules
hc unrule -F
hc rule class=Firefox tag=2
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors
