#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/feh/fehbg &

bspc monitor -d Based

bspc config border_width		2
bspc config window_gap			12

bspc config borderless_monocle		false
bspc config gapless_monocle		false
bspc config focused_border_color	"#d0021b"

bspc desktop -l monocle
