#!/bin/sh

_() {
    bspc config "$@"
}

bspc monitor -d Based

_ border_width         4
_ window_gap           4
_ split_ratio          0.50
_ borderless_monocle   false
_ gapless_monocle      false
_ focused_border_color "#1a1a1a"
_ normal_border_color  "#323232"

feh --randomize --bg-scale ~/.config/wallpapers/*
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
