#! /bin/sh

sxhkd &

bspc monitor -d I II III IV 

bspc config border_width     	      4
bspc config window_gap             20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a qutebrowser state=floating


