#!/bin/sh

$HOME/.fehbg &
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &

bspc monitor -d I

bspc config border_width         2
bspc config window_gap           12

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Emacs state=tiled
