#!/bin/sh

# set brightness
# xbacklight -set 20% &

export PATH=$PATH:"$HOME/.local/bin"

xmodmap ~/.Xmodmap &

# Load the default Guix profile
GUIX_PROFILE="$HOME/.guix-profile"
. "$GUIX_PROFILE"/etc/profile

# Load additional Guix profiles
GUIX_EXTRA_PROFILES=$HOME/.guix-extra-profiles
for i in $GUIX_EXTRA_PROFILES/*; do
  profile=$i/$(basename "$i")
  if [ -f "$profile"/etc/profile ]; then
    GUIX_PROFILE="$profile"
    . "$GUIX_PROFILE"/etc/profile
  fi
  unset profile
done

# Start Shepherd to manage user daemons
if [ -z "$(pgrep -u josegpt shepherd)" ]; then
  shepherd &
fi

# Make sure we can reach the GPG agent for SSH auth
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

exec emacs
