#!/bin/sh

# Start Shepherd to manage user daemons
if [ -z "$(pgrep -u josegpt shepherd)" ]; then
  shepherd &
fi

# Make Caps Lock a Control key
setxkbmap -option ctrl:nocaps

xhost +SI:localuser:$USER

exec emacs
