#!/bin/sh

# Start Shepherd to manage user daemons
if [ -z "$(pgrep -u josegpt shepherd)" ]; then
  shepherd &
fi

# Compositor
picom &

# Make Caps Lock a Control key
setxkbmap -option ctrl:nocaps

xhost +SI:localuser:$USER

# Set Wallpaper
feg --bg-scale $HOME/.wallpapers/current.jpg
~/.fehbg &

exec emacs
